// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Odev_A_13.Context;

#nullable disable

namespace Odev_A_13.Migrations
{
    [DbContext(typeof(ArabaDbContext))]
    partial class ArabaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArabaEngineer", b =>
                {
                    b.Property<int>("ArabalarId")
                        .HasColumnType("int");

                    b.Property<int>("EngineersId")
                        .HasColumnType("int");

                    b.HasKey("ArabalarId", "EngineersId");

                    b.HasIndex("EngineersId");

                    b.ToTable("ArabaEngineer");
                });

            modelBuilder.Entity("Odev_A_13.Models.Araba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("PlakaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("PlakaId")
                        .IsUnique();

                    b.ToTable("Arabalar");
                });

            modelBuilder.Entity("Odev_A_13.Models.Engineer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Engineers");
                });

            modelBuilder.Entity("Odev_A_13.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Odev_A_13.Models.Plaka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArabaId")
                        .HasColumnType("int");

                    b.Property<string>("PlakaNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plakalar");
                });

            modelBuilder.Entity("ArabaEngineer", b =>
                {
                    b.HasOne("Odev_A_13.Models.Araba", null)
                        .WithMany()
                        .HasForeignKey("ArabalarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Odev_A_13.Models.Engineer", null)
                        .WithMany()
                        .HasForeignKey("EngineersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Odev_A_13.Models.Araba", b =>
                {
                    b.HasOne("Odev_A_13.Models.Person", "Person")
                        .WithMany("Arabalar")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Odev_A_13.Models.Plaka", "Plaka")
                        .WithOne("Araba")
                        .HasForeignKey("Odev_A_13.Models.Araba", "PlakaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Plaka");
                });

            modelBuilder.Entity("Odev_A_13.Models.Person", b =>
                {
                    b.Navigation("Arabalar");
                });

            modelBuilder.Entity("Odev_A_13.Models.Plaka", b =>
                {
                    b.Navigation("Araba")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
