// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ODEV_A_13;

#nullable disable

namespace ODEV_A_13.Migrations
{
    [DbContext(typeof(AracDbContext))]
    partial class AracDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ArabaMuhendis", b =>
                {
                    b.Property<int>("ArabalarId")
                        .HasColumnType("int");

                    b.Property<int>("MuhendislerId")
                        .HasColumnType("int");

                    b.HasKey("ArabalarId", "MuhendislerId");

                    b.HasIndex("MuhendislerId");

                    b.ToTable("ArabaMuhendis");
                });

            modelBuilder.Entity("ODEV_A_13.Araba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KisiId")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlakaId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KisiId");

                    b.HasIndex("PlakaId")
                        .IsUnique();

                    b.ToTable("Araba");
                });

            modelBuilder.Entity("ODEV_A_13.Kisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kisi");
                });

            modelBuilder.Entity("ODEV_A_13.Muhendis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Muhendis");
                });

            modelBuilder.Entity("ODEV_A_13.Plaka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PlakaNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plaka");
                });

            modelBuilder.Entity("ArabaMuhendis", b =>
                {
                    b.HasOne("ODEV_A_13.Araba", null)
                        .WithMany()
                        .HasForeignKey("ArabalarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ODEV_A_13.Muhendis", null)
                        .WithMany()
                        .HasForeignKey("MuhendislerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ODEV_A_13.Araba", b =>
                {
                    b.HasOne("ODEV_A_13.Kisi", "Kisi")
                        .WithMany("Arabalar")
                        .HasForeignKey("KisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ODEV_A_13.Plaka", "Plaka")
                        .WithOne("Araba")
                        .HasForeignKey("ODEV_A_13.Araba", "PlakaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kisi");

                    b.Navigation("Plaka");
                });

            modelBuilder.Entity("ODEV_A_13.Kisi", b =>
                {
                    b.Navigation("Arabalar");
                });

            modelBuilder.Entity("ODEV_A_13.Plaka", b =>
                {
                    b.Navigation("Araba")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
